---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config-dev
  labels:
    app: postgresql-dev
data:
  POSTGRESQL_DATABASE: postgresdb
  POSTGRESQL_USER: postgresadmin
  POSTGRESQL_PASSWORD: admin123
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-pv-dev-claim
  labels:
    app: postgresql-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-dev
  template:
    metadata:
      labels:
        app: postgresql-dev
    spec:
      containers:
        - name: postgresql-dev
          image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:10-el8
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-config-dev
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgresql-dev
      volumes:
        - name: postgresql-dev
          persistentVolumeClaim:
            claimName: pg-pv-dev-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-dev
  labels:
    app: postgresql-dev
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgresql-dev
